### ISSUE TITLE
cactbot兼容性问题

### ISSUE THREAD

**Issue by JohnZhang1810** [TundraWork/FFXIV_ACT_Plugin_CN#16]
使用原版ACT 3.6.2.279配合2.23.9.1版本（6.40）解析插件时，cactbot无法加载，OverlayPlugin日志报错：

```
Error: LoadAddons: CactbotOverlay.dll: System.IO.FileLoadException: 未能加载文件或程序集“FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50”或它的某一个依赖项。需要强名称程序集。 (异常来自 HRESULT:0x80131044)
文件名:“FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50” ---> System.IO.FileLoadException: 需要强名称程序集。 (异常来自 HRESULT:0x80131044)
   在 Cactbot.FFXIVPlugin.RegisterProcessChangedHandler(Action`1 handler)
   在 Cactbot.CactbotEventSource.Start()
   在 RainbowMage.OverlayPlugin.Registry.StartEventSource[T](T source)
   在 RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
```

所有插件版本皆为当前时间最新，尝试过使用CafeACT和呆萌ACT中的解析插件载入原版ACT，都无法使用。

**Comment by sandtechnology** [comment]
此问题为.net构建有修改默认使用强签名导致，之前已有人处理并向上游提交了，但是未发布新版本：https://github.com/quisquous/cactbot/pull/5806
可以考虑自行构建或者使用我这个刚刚构建好的版本看看
[cactbot-0.29.25-selfbuild.zip](https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/files/12781800/cactbot-0.29.25-selfbuild.zip)

**Comment by JohnZhang1810** [comment]
> 此问题为.net构建有修改默认使用强签名导致，之前已有人处理并向上游提交了，但是未发布新版本：[quisquous/cactbot#5806](https://github.com/quisquous/cactbot/pull/5806) 可以考虑自行构建或者使用我这个刚刚构建好的版本看看（更新了selfbuild2版本 之前的版本web版本替换错了） [cactbot-0.29.25-selfbuild2.zip](https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/files/12781809/cactbot-0.29.25-selfbuild2.zip)

好的，麻烦了，我这边找个时间测测看

**Comment by enderneko** [comment]
> 此问题为.net构建有修改默认使用强签名导致，之前已有人处理并向上游提交了，但是未发布新版本：[quisquous/cactbot#5806](https://github.com/quisquous/cactbot/pull/5806) 可以考虑自行构建或者使用我这个刚刚构建好的版本看看（更新了selfbuild2版本 之前的版本web版本替换错了） [cactbot-0.29.25-selfbuild2.zip](https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/files/12781809/cactbot-0.29.25-selfbuild2.zip)

试了 cactbot 的 0.30.0、0.30.1、0.30.2 都依然不行，包括你构建的那个我也试了，是我的原版ACT有问题么？
```
Error: LoadAddons: CactbotOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'FFXIV_ACT_Plugin.Common, Version=2.2.0.5, Culture=neutral, PublicKeyToken=9f740ac505d6bc50' ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at Cactbot.FFXIVPlugin.RegisterProcessChangedHandler(Action`1 handler)
   at Cactbot.CactbotEventSource.Start()
   at RainbowMage.OverlayPlugin.Registry.StartEventSource[T](T source)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
```
在 0.30.0 的更新记录中确实提到了
```
plugin: disable strong name req for FFXIV_ACT_Plugin.Common by @Echoring in https://github.com/quisquous/cactbot/pull/5806
```

**Comment by TundraWork** [comment]
> 在 0.30.0 的更新记录中确实提到了
> 
> ```
> plugin: disable strong name req for FFXIV_ACT_Plugin.Common by @Echoring in https://github.com/quisquous/cactbot/pull/5806
> ```

Seems like the fix on their end didn't actually work. Will look into it later.

**Comment by za10087logo** [comment]
请问这个问题有办法解决吗，更新7.0之后还是无法兼容catbot

**Comment by sandtechnology** [comment]
> 请问这个问题有办法解决吗，更新7.0之后还是无法兼容catbot

简单测试了一下，除非上游 [cactbot](https://github.com/OverlayPlugin/cactbot/) 在编译时对 FFXIV_ACT_Plugin.Common 使用不带强签名的依赖或者对编译出来的 CactbotEventSource.dll 中 FFXIV_ACT_Plugin.Common 的引用去除强签名之外，没有其他方法可以解决此问题。
这是一个去除强签名引用的可作为临时使用的 CactbotEventSource.dll，可做替换测试 （https://github.com/OverlayPlugin/cactbot/commit/b284810b05f9d5587a8e32ecf1c1eaa7db7fbe89）
